---
title: "Heart-Failure"
author: "José Luis Tello"
date: "26/8/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readr)
library(skimr)
library(corrplot)
```



### Limpieza y transformacion de datos 

```{r}
df <- read_csv("data/heart_failure.csv")
```


```{r}
sum(is.na(df))
```

```{r}
str(df)
```


```{r}
df$anaemia <- as.factor(df$anaemia)
df$diabetes <- as.factor(df$diabetes)
df$high_blood_pressure <- as.factor(df$high_blood_pressure)
df$sex <- as.factor(df$sex)
df$smoking <- as.factor(df$smoking)
df$DEATH_EVENT <- as.factor(df$DEATH_EVENT)
```

```{r}
str(df)
```

### Analisis de datos!

```{r}
skim(df)
```


```{r}
df %>% 
  group_by(sex, age) %>% 
  count(age,
        sort = TRUE,
        name = "Total") 
```

```{r}
summary(df)
```


```{r}
df %>% 
  select(creatinine_phosphokinase, ejection_fraction, platelets,
         serum_sodium, serum_creatinine) %>% 
  plot()
```


```{r}
ggplot(df, aes(x = serum_sodium)) + 
  geom_histogram(binwidth = 1, colour = "black", fill = "aquamarine3", alpha = 1) +
  geom_density(eval(bquote(aes(y = ..count.. * 1))), colour = "white", fill = "aquamarine4", alpha = 0.35) +
  geom_vline(xintercept = median(df$serum_sodium), linetype="longdash") +
  annotate(geom = "text",
           x = min(df$serum_sodium)+4, y = 36,
           label = str_c("Minimo.     : ", min(df$serum_sodium),
                         "\nMedianana : ", median(df$serum_sodium),
                         "\nPromedio    : ", round(mean(df$serum_sodium), 1),
                         "\nMaximo.    : ", max(df$serum_sodium))) +
  labs(title = "Distribucion del suero de sodio") +
  theme_classic()
```


```{r}
ggplot(df, aes(x = ejection_fraction, fill = DEATH_EVENT)) + 
  geom_density(alpha = 0.64)
```


```{r}
ggplot(df, aes(x = age, fill = sex)) +
  geom_density(alpha = 1,
               color = "white") + 
  labs(title = "Participantes por edad") +
  theme_classic()
```



```{r}
ggplot(df, 
       aes(x = age, 
           fill = DEATH_EVENT)) +
  geom_histogram(alpha = 1,
                 color = "white",
                 bins = 20) +
  labs(title="Histograma de edades con evento de muerte",
       x="Edades",
       y="Total") +
  theme_classic()
```

```{r}
ggplot(df, 
       aes(x = ejection_fraction, 
           fill = DEATH_EVENT)) +
  geom_histogram(alpha = 1,
                 color = "white",
                 bins = 12) +
  labs (title="Porcentaje de sangre que abandona el corazon por bombeo",
        x="",
        y="Total") + 
  theme_classic()

```


```{r}

```


### Modelaje de datos


```{r}
library(tidymodels)
library(rpart)
```

```{r}
library(rpart)
```


```{r}
set.seed(0)
df_split <- initial_split(df)
df_train <- training(df_split)
df_test <- testing(df_split)
```

```{r}
model1 <- rpart(DEATH_EVENT ~ diabetes, data = df_train, method="class")
```

```{r}
library(caret)
options(digits = 4)
```

```{r}
library(e1071)
```


```{r}
Predict_model1_train <- predict(model1, df_train, type = "class")
```

```{r}
conMat <- confusionMatrix(as.factor(Predict_model1_train), as.factor(df_train$DEATH_EVENT))
```

```{r}
conMat$table
```

```{r}
predict_train_accuracy <- conMat$overall["Accuracy"]
predict_train_accuracy
```


